### ISSUE TITLE
Default.css is returning 404 on Local Dev

### ISSUE THREAD

**Issue by TRexStark** [limbo-works/Limbo.Umbraco.Separator#1]
Hi @abjerner

There isn't much to outline as the subject speaks for itself 🙂

**Comment by abjerner** [comment]
@TRexStark thanks for reporting. But remember that even though you think the subject speaks for it self, it's always helpful including what version of Umbraco you're on and what version of the package you're using.

Anyways - in this case, I can confirm it's a general issue affecting `v1.0.2`. I've pushed a new [`v1.0.3`](https://github.com/limbo-works/Limbo.Umbraco.Separator/releases/tag/v1.0.3) release that fixes this 😉

**Comment by TRexStark** [comment]
Thanks @abjerner for attending to this so swiftly. Noted Re: version, sorry haven't thought of that while multi-tasking
